<?php

use Drupal\Core\Entity\EntityInterface;
use Drupal\digitalia_ltp_adapter\DigitaliaLtpUtils;
use Drupal\node\Entity\Node;


/**
 * Transfer published objects to Archivematica
 *
 * implements hook_entity_update()
 */
function digitalia_ltp_adapter_entity_update(EntityInterface $entity)
{
	dpm("Entity update hook");
	\Drupal::logger('digitalia_ltp_adapter')->debug("Entity update hook");
	\Drupal::logger('digitalia_ltp_adapter')->debug("Bundle: " . $entity->bundle());

	$utils = new DigitaliaLtpUtils();
	$utils->updateEntity($entity, $utils::UPDATE_CREATE);
}

/**
 * Transfer published objects to Archivematica
 *
 * implements hook_entity_insert()
 */
function digitalia_ltp_adapter_entity_insert(EntityInterface $entity)
{
	dpm("Entity insesrt hook");
	\Drupal::logger('digitalia_ltp_adapter')->debug("Entity insert hook");
	\Drupal::logger('digitalia_ltp_adapter')->debug("Bundle: " . $entity->bundle());

	$utils = new DigitaliaLtpUtils();
	$utils->updateEntity($entity, $utils::UPDATE_CREATE);
}

/**
 * Transfer deleted objects to Archivematica and mark them as deleted
 *
 * implements hook_entity_predelete()
 */
function digitalia_ltp_adapter_entity_predelete(EntityInterface $entity)
{
	dpm("Entity predelete hook");
	\Drupal::logger('digitalia_ltp_adapter')->debug("Entity predelete hook");
	\Drupal::logger('digitalia_ltp_adapter')->debug("Bundle: " . $entity->bundle());

	$utils = new DigitaliaLtpUtils();
	$utils->updateEntity($entity, $utils::UPDATE_DELETE);
}

/**
 * implements hook_cron()
 */
function digitalia_ltp_adapter_cron()
{
	dpm("Cron hook");
}
