digitalia_ltp_adapter.admin_settings:
  type: config_object
  label: 'Digitalia LTP Adapter config'
  mapping:
    test_field:
      type: text
    site_name:
      type: textfield
    field_configuration:
      type: textarea
    enabled_ltp_systems:
      type: radios
    only_published:
      type: checkbox
    enable_export:
      type: checkbox
