digitalia_ltp_adapter.admin_settings:
  type: config_object
  label: 'Digitalia LTP Adapter config'
  mapping:
    test_field:
      type: text
      label: 'Test field'
    base_url:
      type: string
      label: 'URL of directory shared with Archivematica'
