digitalia_ltp_adapter_arclib.settings:
  type: config_object
  label: 'Arclib LTP Adapter config'
  mapping:
    arc_host:
      type: textfield
    username:
      type: textfield
    password:
      type: password
    base_url:
      type: textfield
    workflow:
      type: textarea
    producer_profile_id:
      type: textfield
    transfer_field:
      type: textfield
    sip_field:
      type: textfield
