digitalia_ltp_adapter_archivematica.settings:
  type: config_object
  label: 'Archivematica LTP Adapter config'
  mapping:
    am_host:
      type: textfield
    api_key_username:
      type: textfield
    api_key_password:
      type: password
    base_url:
      type: textfield
    am_shared_path:
      type: textfield
    processing_config:
      type: textfield
    transfer_field:
      type: textfield
    sip_field:
      type: textfield
