digitalia_ltp_adapter_archivematica.settings:
  type: config_object
  label: 'Archivematica LTP Adapter config'
  mapping:
    am_host:
      type: string
      label: 'Archivematica host URL'
    api_key_username:
      type: string
      label: 'Archivematica username'
    api_key_password:
      type: string
      label: 'Archivematica password'
    base_url:
      type: string
      label: 'URL of directory shared with Archivematica'
